export const BOOKING_ACTIONS = {
   
    // teacher list
    FETCH_TEACHER_LIST: 'FETCH_TEACHER_LIST',
    SET_TEACHER_LIST: 'SET_TEACHER_LIST',

    // bookings
    POST_BOOKING: 'POST_BOOKING',
    BOOKING_SUCCESS: 'BOOKING_SUCCESS',
    BOOKING_FAILURE: 'BOOKING_FAILURE',
    BOOKING_RESET: 'BOOKING_RESET',
    UPDATE_BOOKING_ACCEPT: 'UPDATE_BOOKING_ACCEPT',
    UPDATE_BOOKING_REJECT: 'UPDATE_BOOKING_REJECT',

    //student profile id
    FETCH_STUDENT_ID: 'FETCH_STUDENT_ID',
    SET_STUDENT_ID: 'SET_STUDENT_ID',
    
    //teacher profile id
    FETCH_TEACHER_ID: 'FETCH_TEACHER_ID',
    SET_TEACHER_ID: 'SET_TEACHER_ID',

    // bookings request list for teachers
    FETCH_BOOKINGS_REQUEST_LIST: 'FETCH_BOOKINGS_REQUEST_LIST',
    SET_BOOKINGS_REQUEST_LIST: 'SET_BOOKINGS_REQUEST_LIST',

    //fetch accepted bookings list for teachers
    FETCH_BOOKINGS_LIST: 'FETCH_BOOKINGS_LIST',
    SET_BOOKINGS_LIST: 'SET_BOOKINGS_LIST',

    //fetch bookings list for student
    FETCH_STUDENT_BOOKINGS_LIST: 'FETCH_STUDENT_BOOKINGS_LIST',
    SET_STUDENT_BOOKINGS_LIST: 'SET_STUDENT_BOOKINGS_LIST'
}