export const PERSON_ACTIONS = {
    // student profile
  FETCH_STUDENT: 'FETCH_STUDENT',
  FETCH_STUDENT_FALIURE: 'FETCH_STUDENT_FAILURE',
  STUDENT_RESET: 'STUDENT_RESET',
  SET_STUDENT: 'SET_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  UPDATE_STUDENT_COMPLETE: 'UPDATE_STUDENT_COMPLETE',
  UPDATE_STUDENT_CALLED: 'UPDATE_STUDENT_CALLED',


  // teacher profile
  FETCH_TEACHER: 'FETCH_TEACHER',
  FETCH_TEACHER_FAILURE: 'FETCH_TEACHER_FAILURE',
  TEACHER_RESET: 'TEACHER_RESET',
  SET_TEACHER: 'SET_TEACHER',
  UPDATE_TEACHER: 'UPDATE_TEACHER',
  UPDATE_TEACHER_COMPLETE: 'UPDATE_TEACHER_COMPLETE',
  UPDATE_TEACHER_CALLED: 'UPDATE_TEACHER_CALLED'

}