export const PERSON_ACTIONS = {
    // student profile
  FETCH_STUDENT: 'FETCH_STUDENT',
  SET_STUDENT: 'SET_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  UPDATE_COMPLETE: 'UPDATE_COMPLETE',
  UPDATE_STUDENT_CALLED: 'UPDATE_STUDENT_CALLED',

  // teacher profile
  FETCH_TEACHER: 'FETCH_TEACHER',
  SET_TEACHER: 'SET_TEACHER',
  UPDATE_TEACHER: 'UPDATE_TEACHER',
  UPDATE_SET_TEACHER: 'UPDATE_SET_TEACHER',

}